apiVersion: v2
name: flyte-binary
description: Chart for basic single Flyte executable deployment

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: v0.2.0  # VERSION
