version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # Skip the folder where your generated/dist code lives
    exclude-paths:
      - "/gen/**"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Skip the folder where your generated/dist code lives
    exclude-paths:
      - "/gen/**"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Skip the folder where your generated/dist code lives
    exclude-paths:
      - "/gen/**"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    # Skip the folder where your generated/dist code lives
    exclude-paths:
      - "/gen/**"
