{{- if .Values.sandbox.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "flyte-sandbox.consoleSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-sandbox.consoleSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: console
          {{- with .Values.sandbox.console.image }}
          image: {{ printf "%s:%s" .repository .tag | quote }}
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /v2
              port: http
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /v2
              port: http
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /v2
              port: http
            periodSeconds: 30
{{- end }}
