// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package config

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (Config) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (Config) mustJsonMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	return string(raw)
}

func (Config) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.Int(fmt.Sprintf("%v%v", prefix, "server.port"), defaultConfig.Server.Port, "Port to bind the HTTP server")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "server.host"), defaultConfig.Server.Host, "Host to bind the HTTP server")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.url"), defaultConfig.RunService.URL, "Internal run service base URL")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.type"), string(defaultConfig.RunService.Auth.Type), "Internal run service authentication type")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.issuerUrl"), defaultConfig.RunService.Auth.IssuerURL, "Internal run service OAuth 2.0 issuer URL")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.clientId"), defaultConfig.RunService.Auth.ClientID, "Internal run service OAuth 2.0 client ID")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.clientSecret"), defaultConfig.RunService.Auth.ClientSecret, "Internal run service OAuth 2.0 client secret")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.clientSecretFile"), defaultConfig.RunService.Auth.ClientSecretFile, "File containing the internal run service OAuth 2.0 client secret")
	cmdFlags.StringSlice(fmt.Sprintf("%v%v", prefix, "runService.auth.scopes"), defaultConfig.RunService.Auth.Scopes, "Internal run service OAuth 2.0 scopes")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "runService.auth.audience"), defaultConfig.RunService.Auth.Audience, "Internal run service OAuth 2.0 token audience")
	return cmdFlags
}
