run:
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gas
    - goconst
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck