log-level: warn
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
structname: ""
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.go"
inpackage: false
outpkg: "mocks"
with-expecter: true
packages:
  # ============================================================================
  # datacatalog
  # ============================================================================
  github.com/flyteorg/flyte/datacatalog/pkg/repositories/interfaces:
    config:
      all: false
      dir: 'datacatalog/pkg/repositories/mocks'
    interfaces:
      ArtifactRepo:
      TagRepo:
      PartitionRepo:
      ReservationRepo:
      DatasetRepo:

  github.com/flyteorg/flyte/datacatalog/pkg/manager/interfaces:
    config:
      all: false
      dir: 'datacatalog/pkg/manager/mocks'
    interfaces:
      ArtifactManager:

  # ============================================================================
  # flytectl
  # ============================================================================
  github.com/flyteorg/flyte/flytectl/pkg/github:
    config:
      all: false
      dir: 'flytectl/pkg/github/mocks'
    interfaces:
      GHRepoService:

  github.com/flyteorg/flyte/flytectl/pkg/visualize:
    config:
      all: true
      dir: 'flytectl/pkg/visualize/mocks'

  github.com/flyteorg/flyte/flytectl/pkg/ext:
    config:
      all: true
      dir: 'flytectl/pkg/ext/mocks'

  github.com/flyteorg/flyte/flytectl/pkg/k8s:
    config:
      all: false
      dir: 'flytectl/pkg/k8s/mocks'
    interfaces:
      ContextOps:

  github.com/flyteorg/flyte/flytectl/pkg/docker:
    config:
      all: true
      dir: 'flytectl/pkg/docker/mocks'

  github.com/flyteorg/flyte/flytectl/cmd/update/interfaces:
    config:
      all: false
      dir: 'flytectl/cmd/update/interfaces/mocks'
    interfaces:
      Updater:

  # ============================================================================
  # flytepropeller
  # ============================================================================
  github.com/flyteorg/flyte/flytepropeller/pkg/compiler/common:
    config:
      all: true
      dir: 'flytepropeller/pkg/compiler/common/mocks'

  github.com/flyteorg/flyte/flytepropeller/events:
    config:
      all: true
      dir: 'flytepropeller/events/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/interfaces:
    config:
      all: false
      dir: 'flytepropeller/pkg/controller/mocks'
      filename: "{{.InterfaceName | snakecase}}.go"
    interfaces:
      Limiter:
      Reservation:

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/executors:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/executors/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/interfaces:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/nodes/interfaces/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/dynamic:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/nodes/dynamic/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/task/resourcemanager:
    config:
      all: false
      dir: 'flytepropeller/pkg/controller/nodes/task/resourcemanager/mocks'
    interfaces:
      RedisClient:

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/gate:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/nodes/gate/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/recovery:
    config:
      all: false
      dir: 'flytepropeller/pkg/controller/nodes/recovery/mocks'
    interfaces:
      Client:

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes:
    config:
      all: false
      dir: 'flytepropeller/pkg/controller/nodes/mocks'
    interfaces:
      OutputResolver:

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/array:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/nodes/array/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/nodes/subworkflow/launchplan:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/nodes/subworkflow/launchplan/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/controller/workflowstore:
    config:
      all: true
      dir: 'flytepropeller/pkg/controller/workflowstore/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/apis/flyteworkflow/v1alpha1:
    config:
      all: true
      dir: 'flytepropeller/pkg/apis/flyteworkflow/v1alpha1/mocks'

  github.com/flyteorg/flyte/flytepropeller/pkg/webhook:
    config:
      all: true
      dir: 'flytepropeller/pkg/webhook/mocks'

  github.com/flyteorg/flyte/flytepropeller/manager/shardstrategy:
    config:
      all: false
      dir: 'flytepropeller/manager/shardstrategy/mocks'
    interfaces:
      ShardStrategy:

  # ============================================================================
  # flytestdlib
  # ============================================================================
  github.com/flyteorg/flyte/flytestdlib/random:
    config:
      all: true
      dir: 'flytestdlib/random/mocks'

  github.com/flyteorg/flyte/flytestdlib/storage:
    config:
      all: false
      dir: 'flytestdlib/storage/mocks'
    interfaces:
      RawStore:
      ReferenceConstructor:
      ComposedProtobufStore:

  github.com/flyteorg/flyte/flytestdlib/fastcheck:
    config:
      all: false
      dir: 'flytestdlib/fastcheck/mocks'
    interfaces:
      Filter:

  github.com/flyteorg/flyte/flytestdlib/utils:
    config:
      all: true
      dir: 'flytestdlib/utils/mocks'

  github.com/flyteorg/flyte/flytestdlib/cache:
    config:
      all: true
      dir: 'flytestdlib/cache/mocks'

  # ============================================================================
  # flyteplugins
  # ============================================================================
  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/webapi:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/webapi/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/plugins/array/awsbatch:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/plugins/array/awsbatch/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/plugins/array/core:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/plugins/array/core/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/plugins/presto/client:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/plugins/presto/client/mocks'
      filename: "{{.InterfaceName | snakecase}}.go"

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/io:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/io/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/internal/webapi:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/internal/webapi/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/k8s:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/k8s/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/catalog:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/catalog/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/workqueue:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/workqueue/mocks'

  github.com/flyteorg/flyte/flyteplugins/go/tasks/pluginmachinery/core:
    config:
      all: true
      dir: 'flyteplugins/go/tasks/pluginmachinery/core/mocks'

  # ============================================================================
  # flyteadmin
  # ============================================================================
  github.com/flyteorg/flyte/flyteadmin/pkg/data/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/data/mocks'
    interfaces:
      RemoteURLInterface:

  github.com/flyteorg/flyte/flyteadmin/pkg/executioncluster/interfaces:
    config:
      all: true
      dir: 'flyteadmin/pkg/executioncluster/mocks'

  github.com/flyteorg/flyte/flyteadmin/pkg/workflowengine/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/workflowengine/mocks'
    interfaces:
      WorkflowExecutor:
      FlyteWorkflowBuilder:

  github.com/flyteorg/flyte/flyteadmin/pkg/manager/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/manager/mocks'
    interfaces:
      TaskInterface:
      WorkflowInterface:
      NamedEntityInterface:
      LaunchPlanInterface:
      TaskExecutionInterface:
      ResourceInterface:
      MetricsInterface:
      VersionInterface:
      ExecutionInterface:
      ProjectInterface:
      NodeExecutionInterface:
      SignalInterface:

  github.com/flyteorg/flyte/flyteadmin/pkg/repositories/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/repositories/mocks'
    interfaces:
      NamedEntityRepoInterface:
      ExecutionEventRepoInterface:
      DescriptionEntityRepoInterface:
      NodeExecutionEventRepoInterface:
      SignalRepoInterface:

  github.com/flyteorg/flyte/flyteadmin/pkg/async/cloudevent/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/async/cloudevent/mocks'
    interfaces:
      Publisher:
      Sender:

  github.com/flyteorg/flyte/flyteadmin/pkg/async/notifications/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/async/notifications/mocks'
    interfaces:
      Publisher:
      SMTPClient:
      Emailer:
      Processor:

  github.com/flyteorg/flyte/flyteadmin/pkg/async/notifications/implementations:
    config:
      all: true
      dir: 'flyteadmin/pkg/async/notifications/mocks'

  github.com/flyteorg/flyte/flyteadmin/pkg/async/events/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/async/events/mocks'
    interfaces:
      NodeExecutionEventWriter:
      WorkflowExecutionEventWriter:

  github.com/flyteorg/flyte/flyteadmin/pkg/async/schedule/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/async/schedule/mocks'
    interfaces:
      WorkflowExecutor:
      EventScheduler:

  github.com/flyteorg/flyte/flyteadmin/pkg/runtime/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/runtime/mocks'
    interfaces:
      QualityOfServiceConfiguration:
      WhitelistConfiguration:
      ClusterConfiguration:
      NamespaceMappingConfiguration:
      ClusterPoolAssignmentConfiguration:

  github.com/flyteorg/flyte/flyteadmin/pkg/clusterresource/interfaces:
    config:
      all: false
      dir: 'flyteadmin/pkg/clusterresource/mocks'
    interfaces:
      FlyteAdminDataProvider:

  github.com/flyteorg/flyte/flyteadmin/scheduler/executor:
    config:
      all: false
      dir: 'flyteadmin/scheduler/executor/mocks'
    interfaces:
      Executor:

  github.com/flyteorg/flyte/flyteadmin/scheduler/repositories/interfaces:
    config:
      all: false
      dir: 'flyteadmin/scheduler/repositories/mocks'
    interfaces:
      ScheduleEntitiesSnapShotRepoInterface:
      SchedulableEntityRepoInterface:

  github.com/flyteorg/flyte/flyteadmin/auth/interfaces:
    config:
      all: true
      dir: 'flyteadmin/auth/interfaces/mocks'

  # ============================================================================
  # flyteidl
  # ============================================================================
  github.com/flyteorg/flyte/flyteidl/gen/pb-go/flyteidl/service:
    config:
      all: false
      dir: 'flyteidl/clients/go/admin/mocks'
    interfaces:
      AdminServiceClient:

  github.com/flyteorg/flyte/flyteidl/clients/go/admin:
    config:
      all: false
      dir: 'flyteidl/clients/go/admin/mocks'
    interfaces:
      TokenSource:

  github.com/flyteorg/flyte/flyteidl/clients/go/admin/cache:
    config:
      all: true
      dir: 'flyteidl/clients/go/admin/cache/mocks'
