# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_install:
      - cat monodocs-environment.lock.yaml
      - conda-lock install --name $READTHEDOCS_VERSION monodocs-environment.lock.yaml
      - pip install ./flyteidl
      - conda info
      - conda env list
      - conda list

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/build-environment.yaml
