---
# Source: flyteconnector/templates/connector/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flyteconnector
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteconnector
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteconnector-v0.1.10
    app.kubernetes.io/managed-by: Helm
---
# Source: flyteconnector/templates/connector/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flyteconnector
  namespace: flyte
type: Opaque
data:
  username: User
---
# Source: flyteconnector/templates/connector/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flyteconnector
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteconnector
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteconnector-v0.1.10
    app.kubernetes.io/managed-by: Helm
  annotations: 
    projectcontour.io/upstream-protocol.h2c: grpc
spec:
  type: ClusterIP
  ports:
  - name: connector-grpc
    port: 8000
    protocol: TCP
    appProtocol: TCP
    targetPort: connector-grpc
  selector: 
    app.kubernetes.io/name: flyteconnector
    app.kubernetes.io/instance: flyte
---
# Source: flyteconnector/templates/connector/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyteconnector
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteconnector
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteconnector-v0.1.10
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: flyteconnector
      app.kubernetes.io/instance: flyte
  template:
    metadata:
      annotations:
      labels: 
        app.kubernetes.io/name: flyteconnector
        app.kubernetes.io/instance: flyte
        helm.sh/chart: flyteconnector-v0.1.10
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
      - command:
        - pyflyte
        - serve
        - agent
        image: "cr.flyte.org/flyteorg/flyteagent:1.15.3"
        imagePullPolicy: "IfNotPresent"
        name: flyteconnector
        volumeMounts:
        - mountPath: /etc/secrets
          name: flyteconnector
        ports:
        - containerPort: 8000
          name: connector-grpc
        readinessProbe:
          grpc:
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 3
        securityContext:
            allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 300Mi
          requests:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 200Mi
      serviceAccountName: flyteconnector
      volumes:
      - name: flyteconnector
        secret:
          secretName: flyteconnector
