// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "github.com/unionai/flyte/fasttask/plugin/interfaces"
)

// EnvironmentStore is an autogenerated mock type for the EnvironmentStore type
type EnvironmentStore struct {
	mock.Mock
}

type EnvironmentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EnvironmentStore) EXPECT() *EnvironmentStore_Expecter {
	return &EnvironmentStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: executionEnvID
func (_m *EnvironmentStore) Delete(executionEnvID string) {
	_m.Called(executionEnvID)
}

// EnvironmentStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EnvironmentStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - executionEnvID string
func (_e *EnvironmentStore_Expecter) Delete(executionEnvID interface{}) *EnvironmentStore_Delete_Call {
	return &EnvironmentStore_Delete_Call{Call: _e.mock.On("Delete", executionEnvID)}
}

func (_c *EnvironmentStore_Delete_Call) Run(run func(executionEnvID string)) *EnvironmentStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EnvironmentStore_Delete_Call) Return() *EnvironmentStore_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *EnvironmentStore_Delete_Call) RunAndReturn(run func(string)) *EnvironmentStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: executionEnvID
func (_m *EnvironmentStore) Get(executionEnvID string) interfaces.Environment {
	ret := _m.Called(executionEnvID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interfaces.Environment
	if rf, ok := ret.Get(0).(func(string) interfaces.Environment); ok {
		r0 = rf(executionEnvID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Environment)
		}
	}

	return r0
}

// EnvironmentStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EnvironmentStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - executionEnvID string
func (_e *EnvironmentStore_Expecter) Get(executionEnvID interface{}) *EnvironmentStore_Get_Call {
	return &EnvironmentStore_Get_Call{Call: _e.mock.On("Get", executionEnvID)}
}

func (_c *EnvironmentStore_Get_Call) Run(run func(executionEnvID string)) *EnvironmentStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EnvironmentStore_Get_Call) Return(_a0 interfaces.Environment) *EnvironmentStore_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EnvironmentStore_Get_Call) RunAndReturn(run func(string) interfaces.Environment) *EnvironmentStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: executionEnvID, env
func (_m *EnvironmentStore) GetOrCreate(executionEnvID string, env interfaces.Environment) interfaces.Environment {
	ret := _m.Called(executionEnvID, env)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 interfaces.Environment
	if rf, ok := ret.Get(0).(func(string, interfaces.Environment) interfaces.Environment); ok {
		r0 = rf(executionEnvID, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Environment)
		}
	}

	return r0
}

// EnvironmentStore_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type EnvironmentStore_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - executionEnvID string
//   - env interfaces.Environment
func (_e *EnvironmentStore_Expecter) GetOrCreate(executionEnvID interface{}, env interface{}) *EnvironmentStore_GetOrCreate_Call {
	return &EnvironmentStore_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", executionEnvID, env)}
}

func (_c *EnvironmentStore_GetOrCreate_Call) Run(run func(executionEnvID string, env interfaces.Environment)) *EnvironmentStore_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interfaces.Environment))
	})
	return _c
}

func (_c *EnvironmentStore_GetOrCreate_Call) Return(_a0 interfaces.Environment) *EnvironmentStore_GetOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EnvironmentStore_GetOrCreate_Call) RunAndReturn(run func(string, interfaces.Environment) interfaces.Environment) *EnvironmentStore_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields:
func (_m *EnvironmentStore) List() []interfaces.Environment {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []interfaces.Environment
	if rf, ok := ret.Get(0).(func() []interfaces.Environment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Environment)
		}
	}

	return r0
}

// EnvironmentStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EnvironmentStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *EnvironmentStore_Expecter) List() *EnvironmentStore_List_Call {
	return &EnvironmentStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *EnvironmentStore_List_Call) Run(run func()) *EnvironmentStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EnvironmentStore_List_Call) Return(_a0 []interfaces.Environment) *EnvironmentStore_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EnvironmentStore_List_Call) RunAndReturn(run func() []interfaces.Environment) *EnvironmentStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewEnvironmentStore creates a new instance of EnvironmentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvironmentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnvironmentStore {
	mock := &EnvironmentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
