helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: flyte-sandbox
  releaseName: flyte-sandbox
  namespace: flyte
namespace: flyte
resources:
- ../namespace.yaml
- ../dashboard-rbac.yaml
patches:
- target:
    kind: Secret
    name: kubernetes-dashboard-csrf
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
