PREFIX=hive
include ../../../common/Makefile
include ../../../common/leaf.mk

.PHONY: docker_build
docker_build: ;

.PHONY: docker_push
docker_push: ;
	
.PHONY: register
register: ;

.PHONY: serialize
serialize: ;

.PHONY: docker_push
docker_push: ;