name: Master

on:
  push:
    branches:
      - master

jobs:
  # Duplicated from pull request workflow because sharing is not yet supported
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: load-docker-cache
        name: Load Docker Cache
        uses: actions/cache@v1
        with:
          path: /tmp/tmp/docker-images
          key: /tmp/docker-images-${{ github.event.after }}
          restore-keys: |
            /tmp/docker-images-${{ github.event.before }}
            /tmp/docker-images-${{ github.event.pull_request.base.sha }}
      - name: Prime docker cache
        run: (docker load -i /tmp/tmp/docker-images/snapshot-builder.tar || true) && (docker load -i /tmp/tmp/docker-images/snapshot.tar || true)
      - name: Build dockerfile
        run: |
          docker build -t lyft/${{ github.event.repository.name }}:builder --target builder --cache-from=lyft/${{ github.event.repository.name }}:builder .
          docker build -t lyft/${{ github.event.repository.name }}:latest --cache-from=lyft/${{ github.event.repository.name }}:builder .

      - name: Tag and cache docker image
        run: mkdir -p /tmp/tmp/docker-images && docker save lyft/${{ github.event.repository.name }}:builder -o /tmp/tmp/docker-images/snapshot-builder.tar && docker save lyft/${{ github.event.repository.name }}:latest -o /tmp/tmp/docker-images/snapshot.tar

  # Duplicated from pull request workflow because sharing is not yet supported
  endtoend:
    name: End to End tests
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: load-docker-cache
        name: Load Docker Cache
        uses: actions/cache@v1
        with:
          path: /tmp/tmp/docker-images
          key: /tmp/docker-images-${{ github.event.after }}
      - name: Prime docker cache
        run: docker load -i /tmp/tmp/docker-images/snapshot.tar || true
      - uses: engineerd/setup-kind@v0.4.0
      - name: End2End
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          IMAGE_NAME=${{ github.event.repository.name }} IMAGE=lyft/${{ github.event.repository.name }}:latest make end2end_execute

  bump-version:
    if: github.actor != 'goreleaserbot'
    runs-on: ubuntu-latest
    needs: build-docker # Only to ensure it can successfully build
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

  push-github-end2end:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: ${{ github.repository }}
          image_tag: latest,${{ github.sha }},${{ needs.bump-version.outputs.version }}
          push_git_tag: true
          registry: docker.pkg.github.com
          build_extra_args: "--compress=true"

  push-dockerhub:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Push Docker Image to Dockerhub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          image_name: ${{ secrets.DOCKERHUB_IMAGE_NAME }}
          image_tag: latest,${{ github.sha }},${{ needs.bump-version.outputs.version }}
          push_git_tag: true
          build_extra_args: "--compress=true"

  tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Unit Tests
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
