// Shared constants for the manager implementation.
package shared

// Field names for reference
const (
	Project               = "project"
	Domain                = "domain"
	Name                  = "name"
	ID                    = "id"
	Version               = "version"
	Spec                  = "spec"
	Type                  = "type"
	RuntimeVersion        = "runtime version"
	Metadata              = "metadata"
	TypedInterface        = "typed interface"
	Container             = "container"
	Image                 = "image"
	Limit                 = "limit"
	Offset                = "offset"
	Filters               = "filters"
	ExpectedInputs        = "expected_inputs"
	FixedInputs           = "fixed_inputs"
	DefaultInputs         = "default_inputs"
	Inputs                = "inputs"
	State                 = "state"
	ExecutionID           = "execution_id"
	NodeID                = "node_id"
	NodeExecutionID       = "node_execution_id"
	TaskID                = "task_id"
	OccurredAt            = "occurred_at"
	Event                 = "event"
	ParentTaskExecutionID = "parent_task_execution_id"
	UserInputs            = "user_inputs"
	ProjectDomain         = "project_domain"
)
