{{- if .Values.dataproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-core.componentFullname" (dict "ctx" $ "component" "dataproxy") }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "flyte-core.componentLabels" (dict "ctx" $ "component" "dataproxy") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.dataproxy.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "flyte-core.selectorLabels" (dict "ctx" $ "component" "dataproxy") | nindent 4 }}
{{- end }}
