{{- if and (not (include "flyte-core.externalConfiguration" .)) .Values.components.secret.enabled }}
{{- $webhookURL := .Values.configuration.secret.webhookURL }}
{{- if and (not $webhookURL) .Values.components.executor.enabled }}
{{- $webhookURL = printf "http://%s:%v" (include "flyte-core.executorCacheServiceHost" .) .Values.configuration.webhook.cacheInvalidationPort }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flyte-core.componentConfigMapName" (dict "root" . "component" "secret") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-core.componentLabels" (dict "root" . "component" "secret") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  000-core.yaml: |
    {{- include "flyte-core.config.logger" . | nindent 4 }}
    secret:
      server:
        {{- toYaml .Values.configuration.secret.server | nindent 8 }}
      kubernetes:
        {{- tpl (toYaml .Values.configuration.kubernetes) . | nindent 8 }}
      webhookURL: {{ $webhookURL | quote }}
  {{- with .Values.configuration.inline }}
  100-inline.yaml: |
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
