{{- if and (not (include "flyte-core.externalConfiguration" .)) .Values.components.secret.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flyte-core.componentConfigMapName" (dict "root" . "component" "secret") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-core.componentLabels" (dict "root" . "component" "secret") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  000-core.yaml: |
    {{- include "flyte-core.config.logger" . | nindent 4 }}
    secret:
      kubernetes:
        {{- tpl (toYaml .Values.configuration.kubernetes) . | nindent 8 }}
      {{- tpl (toYaml .Values.configuration.secret) . | nindent 6 }}
  {{- with .Values.configuration.inline }}
  100-inline.yaml: |
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
