{{- if .Values.rustfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rustfs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-devbox.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.rustfs.accessKey | b64enc | quote }}
  secret-key: {{ .Values.rustfs.secretKey | b64enc | quote }}
{{- end }}
