version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flyte-runs-postgres
    environment:
      POSTGRES_DB: flyte_runs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  runs-service:
    build:
      context: ..
      dockerfile: runs/Dockerfile
    container_name: flyte-runs-service
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    volumes:
      - ./config-postgres.yaml:/app/config.yaml
    command: ["--config", "config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
