// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package clustered

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (Config) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (Config) mustJsonMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	return string(raw)
}

func (Config) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "startup-timeout"), defaultConfig.StartupTimeout.String(), "Per-worker wait for peers; 0 keeps the launcher's.")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "kueue.enabled"), defaultConfig.Kueue.Enabled, "Create JobSets suspended and labelled for Kueue.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "kueue.queue-name"), defaultConfig.Kueue.QueueName, "Kueue LocalQueue that every clustered JobSet is submitted to.")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "kueue.evict-as-system-retry"), defaultConfig.Kueue.EvictAsSystemRetry, "Report evictions of a running gang as system retries.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "kueue.admission-timeout"), defaultConfig.Kueue.AdmissionTimeout.String(), "Retry a JobSet suspended this long; 0 disables.")
	return cmdFlags
}
