name: Housekeeping
description: Maintenance and cleanup tasks that need to be performed may include tech debt, library upgrades, CI/CD improvements, etc.
title: "[Housekeeping] "
labels: housekeeping
body:
  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: "Describe the issue"
      description: "A clear and concise description of what the housekeeping item is."
      placeholder: "Clean up [...] OR upgrade [...] library to pull in the latest changes, etc."
  - type: textarea
    id: consequences
    validations:
      required: true
    attributes:
      label: "What if we do not do this?"
      description: "Short description of potential consequences"
      placeholder: "Higher propensity for errors, uncleanliness, lack of polish, [...]"
  - type: textarea
    id: related-component
    validations:
      required: false
    attributes:
      label: "Related component(s)"
      description: "Either specific or all"
      placeholder: "flyteidl, [...]"
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      options:
        - label: "Are you sure this issue hasn't been raised already?"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?"
      options:
        - label: "Yes"
        - label: "No"
          required: true
