name: UI Feature request
description: Suggest a feature in the UI
title: "[UI Feature]"
labels: enhancement, untriaged, ui
body:
  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: "Motivation: Why do you think this is important?"
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm frustrated when [...] OR this feature can be a cool addition because [...] OR this feature can simplify [...] use case."
  - type: textarea
    id: goal
    validations:
      required: true
    attributes:
      label: "Goal: What should the final outcome look like, ideally?"
      description: "A clear and concise description of what you want to happen or achieve."
      placeholder: "This feature can help implement or resolve [...]"
  - type: textarea
    id: context
    validations:
      required: false
    attributes:
      label: "Propose: Link/Inline OR Additional context "
      description: "If you have ideas about the implementation, please propose the change. If inline, keep it short; if more prominent, then you can link to an external document."
 - type: checkboxes
    id: no-duplicate-issues
    attributes:
      options:
        - label: "Are you sure this issue hasn't been raised already?"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      options:
        - label: "Have you read the [Code of Conduct]( https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?"
          required: true
