{{- if and (not (include "flyte-core.externalConfiguration" .)) .Values.components.executor.enabled }}
{{- $executorConfig := omit .Values.configuration.executor "metricsPort" "healthProbePort" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flyte-core.componentConfigMapName" (dict "root" . "component" "executor") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-core.componentLabels" (dict "root" . "component" "executor") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  000-core.yaml: |
    {{- include "flyte-core.config.logger" . | nindent 4 }}
    actions:
      kubernetes:
        {{- tpl (toYaml .Values.configuration.kubernetes) . | nindent 8 }}
    executor:
      metricsBindAddress: {{ printf ":%v" .Values.configuration.executor.metricsPort | quote }}
      healthProbeBindAddress: {{ printf ":%v" .Values.configuration.executor.healthProbePort | quote }}
      {{- with $executorConfig }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
    webhook:
      localCert: true
      certDir: /var/run/flyte/certs
      secretName: {{ include "flyte-core.webhookSecretName" . }}
      serviceName: {{ include "flyte-core.componentName" (dict "root" . "component" "executor") }}
      servicePort: {{ .Values.configuration.webhook.listenPort }}
      secretManagerTypes:
        - Embedded
      embeddedSecretManagerConfig:
        type: K8s
        k8sConfig:
          namespace: {{ tpl .Values.configuration.kubernetes.namespace . }}
      {{- with .Values.configuration.webhook }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  001-plugins.yaml: |
    tasks:
      {{- toYaml .Values.enabledPlugins.tasks | nindent 6 }}
  003-storage.yaml: |
    {{- include "flyte-core.config.storage" . | nindent 4 }}
  {{- with .Values.configuration.inline }}
  100-inline.yaml: |
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
