apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  labels: {{- include "flyte-devbox.labels" . | nindent 4 }}
spec:
  valuesContent: |
    service:
      type: NodePort
    ports:
      web:
        nodePort: 30080
        transport:
          respondingTimeouts:
            readTimeout: 0
      apps:
        port: 30081
        nodePort: 30081
        expose:
          default: true
        transport:
          respondingTimeouts:
            readTimeout: 0
      websecure:
        expose: false
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true
