// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NamespaceMappingConfiguration is an autogenerated mock type for the NamespaceMappingConfiguration type
type NamespaceMappingConfiguration struct {
	mock.Mock
}

type NamespaceMappingConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *NamespaceMappingConfiguration) EXPECT() *NamespaceMappingConfiguration_Expecter {
	return &NamespaceMappingConfiguration_Expecter{mock: &_m.Mock}
}

// GetNamespaceTemplate provides a mock function with given fields:
func (_m *NamespaceMappingConfiguration) GetNamespaceTemplate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceTemplate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NamespaceMappingConfiguration_GetNamespaceTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaceTemplate'
type NamespaceMappingConfiguration_GetNamespaceTemplate_Call struct {
	*mock.Call
}

// GetNamespaceTemplate is a helper method to define mock.On call
func (_e *NamespaceMappingConfiguration_Expecter) GetNamespaceTemplate() *NamespaceMappingConfiguration_GetNamespaceTemplate_Call {
	return &NamespaceMappingConfiguration_GetNamespaceTemplate_Call{Call: _e.mock.On("GetNamespaceTemplate")}
}

func (_c *NamespaceMappingConfiguration_GetNamespaceTemplate_Call) Run(run func()) *NamespaceMappingConfiguration_GetNamespaceTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NamespaceMappingConfiguration_GetNamespaceTemplate_Call) Return(_a0 string) *NamespaceMappingConfiguration_GetNamespaceTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NamespaceMappingConfiguration_GetNamespaceTemplate_Call) RunAndReturn(run func() string) *NamespaceMappingConfiguration_GetNamespaceTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewNamespaceMappingConfiguration creates a new instance of NamespaceMappingConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNamespaceMappingConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *NamespaceMappingConfiguration {
	mock := &NamespaceMappingConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
