{{- if .Values.concurrency_controller.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-concurrency-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteconcurrency.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.admin }}
  admin.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.db.admin }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.concurrencyConfig }}
  server.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configmap.logger }}
  logger.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }} 