{{- if and .Values.concurrency_controller.enabled .Values.flyteconcurrency.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flyteconcurrency.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteconcurrency.labels" . | nindent 4 }}
  {{- with .Values.flyteconcurrency.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }} 