---
# MinIO Deployment for Data Proxy Development
# This is a simple single-node MinIO deployment for local testing and development.
# For production use, please refer to MinIO's official deployment guides.

apiVersion: v1
kind: Namespace
metadata:
  name: flyte-dataproxy
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte-dataproxy
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte-dataproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
---
# Optional: Port forward service for local access
# Run: kubectl port-forward -n flyte-dataproxy svc/minio 9000:9000 9001:9001
# Then access:
#   - MinIO API: http://localhost:9000
#   - MinIO Console: http://localhost:9001
