{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flyte-binary.rbac.clusterRoleName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.labels }}
    {{- tpl ( .Values.rbac.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- tpl ( .Values.rbac.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - resourcequotas
    - secrets
    - serviceaccounts
    verbs:
    - create
    - get
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - podtemplates
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - flyte.lyft.com
    resources:
    - flyteworkflows
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - post
    - update
    - watch
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - create
    - get
    - list
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    verbs:
    - create
    - get
    - list
    - patch
    - update
  {{- if .Values.rbac.extraRules }}
  {{- toYaml .Values.rbac.extraRules | nindent 2 }}
  {{- end }}
{{- end }}
