{{- if and ( not ( index .Values "flyte-binary" "enabled" ) ) .Values.sandbox.dev .Values.sandbox.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-devbox.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-devbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "flyte-devbox.consoleSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-devbox.consoleSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: console
          image: "{{ .Values.sandbox.console.image.repository }}:{{ .Values.sandbox.console.image.tag }}"
          imagePullPolicy: {{ .Values.sandbox.console.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.sandbox.console.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.sandbox.console.basePath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-devbox.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-devbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  ports:
    - name: http
      port: {{ .Values.sandbox.console.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "flyte-devbox.consoleSelectorLabels" . | nindent 4 }}
{{- end }}
