helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: flyte-sandbox
  releaseName: flyte-sandbox
  namespace: flyte
  valuesInline:
    flyte-binary:
      enabled: false
    sandbox:
      dev: true
namespace: flyte
resources:
- ../namespace.yaml
- ../../../../charts/flyte-binary/templates/crds/flyte.org_taskactions.yaml
- ../dashboard-rbac.yaml
patches:
- target:
    kind: Secret
    name: kubernetes-dashboard-csrf
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: Deployment
    name: flyte-sandbox-kubernetes-dashboard
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: Service
    name: flyte-sandbox-kubernetes-dashboard
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: ServiceAccount
    name: flyte-sandbox-kubernetes-dashboard
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: Secret
    name: flyte-sandbox-kubernetes-dashboard-certs
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: Secret
    name: kubernetes-dashboard-key-holder
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: ConfigMap
    name: kubernetes-dashboard-settings
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: Role
    name: flyte-sandbox-kubernetes-dashboard
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- target:
    kind: RoleBinding
    name: flyte-sandbox-kubernetes-dashboard
  patch: |
    - op: add
      path: /metadata/namespace
      value: flyte
- path: ../minio-patch.yaml
