helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: flyte-sandbox
  namespace: flyte
  releaseName: flyte-sandbox
  valuesInline:
    flyte-binary:
      enabled: false
    sandbox:
      dev: true
namespace: flyte
resources:
- ../namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
