# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = flytekit
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

gendocs:
	go build -o ../bin/flytectl-docs $(SOURCEDIR)/generate_docs.go
	rm -rf $(SOURCEDIR)/gen
	mkdir gen
	../bin/flytectl-docs
	mv gen $(SOURCEDIR)
	make html

clean:
	rm -rf $(SOURCEDIR)/gen
	rm -rf build/*

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
