{{- if .Values.flyteadmin.enabled }}
{{- $secret := (lookup "v1" "Secret" (include "flyte.namespace" .) "flyte-admin-secrets") -}}
apiVersion: v1
kind: Secret
metadata:
  name: flyte-admin-secrets
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
data:
{{- if $secret }}
  token_rsa_key.pem: |
    {{ index $secret.data "token_rsa_key.pem" }}
  cookie_hash_key: {{ index $secret.data "cookie_hash_key" }}
  cookie_block_key: {{ index $secret.data "cookie_block_key" }}
  claim_symmetric_key: {{ index $secret.data "claim_symmetric_key" }}
  oidc_client_secret: {{ index $secret.data "oidc_client_secret" }}
{{- else }}
  token_rsa_key.pem: |
    {{ genPrivateKey "rsa" | b64enc }}
{{- end }}
stringData:
{{- if not $secret }}
  cookie_hash_key: {{ trimSuffix "==" (randBytes 64) | quote }}
  cookie_block_key: {{ trimSuffix "=" (randBytes 32) | quote }}
  claim_symmetric_key: {{ trimSuffix "=" (randBytes 32) | quote }}
{{- if .Values.secrets.adminOauthClientCredentials.enabled }}
  oidc_client_secret: {{ .Values.secrets.adminOauthClientCredentials.clientSecret | quote }}
{{- end }}
{{- end }}
{{- with .Values.flyteadmin.secrets -}}
{{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
