{{- if not (include "flyte-core.externalConfiguration" .) }}
{{- if and .Values.configuration.database.postgres.password .Values.configuration.database.postgres.passwordPath }}
{{- fail "configuration.database.postgres.password and passwordPath are mutually exclusive" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyte-core.configSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-core.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.configuration.database.postgres.password }}
  012-database-secrets.yaml: |
    database:
      postgres:
        password: {{ . | quote }}
    runs:
      database:
        postgres:
          password: {{ . | quote }}
  {{- end }}
  {{- if and (eq "s3" .Values.configuration.storage.provider) (eq "accesskey" .Values.configuration.storage.providerConfig.s3.authType) }}
  013-storage-secrets.yaml: |
    storage:
      stow:
        config:
          access_key_id: {{ required "S3 accessKey is required for accesskey authentication" .Values.configuration.storage.providerConfig.s3.accessKey | quote }}
          {{- if .Values.configuration.storage.providerConfig.s3.secretKey }}
          secret_key: {{ .Values.configuration.storage.providerConfig.s3.secretKey | quote }}
          {{- else if .Values.configuration.storage.providerConfig.s3.secretKeyPath }}
          secret_key_path: {{ .Values.configuration.storage.providerConfig.s3.secretKeyPath | quote }}
          {{- else }}
          {{- fail "S3 secretKey or secretKeyPath is required for accesskey authentication" }}
          {{- end }}
  {{- end }}
  {{- if and (eq "azure" .Values.configuration.storage.provider) .Values.configuration.storage.providerConfig.azure.key }}
  013-storage-secrets.yaml: |
    storage:
      stow:
        config:
          key: {{ .Values.configuration.storage.providerConfig.azure.key | quote }}
  {{- end }}
{{- end }}
