{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyte-core.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "flyte-core.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
