// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	admin "github.com/flyteorg/flyteidl/gen/pb-go/flyteidl/admin"

	mock "github.com/stretchr/testify/mock"
)

// AsyncAgentServiceServer is an autogenerated mock type for the AsyncAgentServiceServer type
type AsyncAgentServiceServer struct {
	mock.Mock
}

type AsyncAgentServiceServer_CreateTask struct {
	*mock.Call
}

func (_m AsyncAgentServiceServer_CreateTask) Return(_a0 *admin.CreateTaskResponse, _a1 error) *AsyncAgentServiceServer_CreateTask {
	return &AsyncAgentServiceServer_CreateTask{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AsyncAgentServiceServer) OnCreateTask(_a0 context.Context, _a1 *admin.CreateTaskRequest) *AsyncAgentServiceServer_CreateTask {
	c_call := _m.On("CreateTask", _a0, _a1)
	return &AsyncAgentServiceServer_CreateTask{Call: c_call}
}

func (_m *AsyncAgentServiceServer) OnCreateTaskMatch(matchers ...interface{}) *AsyncAgentServiceServer_CreateTask {
	c_call := _m.On("CreateTask", matchers...)
	return &AsyncAgentServiceServer_CreateTask{Call: c_call}
}

// CreateTask provides a mock function with given fields: _a0, _a1
func (_m *AsyncAgentServiceServer) CreateTask(_a0 context.Context, _a1 *admin.CreateTaskRequest) (*admin.CreateTaskResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *admin.CreateTaskResponse
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateTaskRequest) *admin.CreateTaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.CreateTaskResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *admin.CreateTaskRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type AsyncAgentServiceServer_DeleteTask struct {
	*mock.Call
}

func (_m AsyncAgentServiceServer_DeleteTask) Return(_a0 *admin.DeleteTaskResponse, _a1 error) *AsyncAgentServiceServer_DeleteTask {
	return &AsyncAgentServiceServer_DeleteTask{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AsyncAgentServiceServer) OnDeleteTask(_a0 context.Context, _a1 *admin.DeleteTaskRequest) *AsyncAgentServiceServer_DeleteTask {
	c_call := _m.On("DeleteTask", _a0, _a1)
	return &AsyncAgentServiceServer_DeleteTask{Call: c_call}
}

func (_m *AsyncAgentServiceServer) OnDeleteTaskMatch(matchers ...interface{}) *AsyncAgentServiceServer_DeleteTask {
	c_call := _m.On("DeleteTask", matchers...)
	return &AsyncAgentServiceServer_DeleteTask{Call: c_call}
}

// DeleteTask provides a mock function with given fields: _a0, _a1
func (_m *AsyncAgentServiceServer) DeleteTask(_a0 context.Context, _a1 *admin.DeleteTaskRequest) (*admin.DeleteTaskResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *admin.DeleteTaskResponse
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteTaskRequest) *admin.DeleteTaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.DeleteTaskResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *admin.DeleteTaskRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type AsyncAgentServiceServer_GetTask struct {
	*mock.Call
}

func (_m AsyncAgentServiceServer_GetTask) Return(_a0 *admin.GetTaskResponse, _a1 error) *AsyncAgentServiceServer_GetTask {
	return &AsyncAgentServiceServer_GetTask{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AsyncAgentServiceServer) OnGetTask(_a0 context.Context, _a1 *admin.GetTaskRequest) *AsyncAgentServiceServer_GetTask {
	c_call := _m.On("GetTask", _a0, _a1)
	return &AsyncAgentServiceServer_GetTask{Call: c_call}
}

func (_m *AsyncAgentServiceServer) OnGetTaskMatch(matchers ...interface{}) *AsyncAgentServiceServer_GetTask {
	c_call := _m.On("GetTask", matchers...)
	return &AsyncAgentServiceServer_GetTask{Call: c_call}
}

// GetTask provides a mock function with given fields: _a0, _a1
func (_m *AsyncAgentServiceServer) GetTask(_a0 context.Context, _a1 *admin.GetTaskRequest) (*admin.GetTaskResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *admin.GetTaskResponse
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetTaskRequest) *admin.GetTaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetTaskResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *admin.GetTaskRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
