// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isGetDataResponse_Data is an autogenerated mock type for the isGetDataResponse_Data type
type isGetDataResponse_Data struct {
	mock.Mock
}

// isGetDataResponse_Data provides a mock function with no fields
func (_m *isGetDataResponse_Data) isGetDataResponse_Data() {
	_m.Called()
}

// newIsGetDataResponse_Data creates a new instance of isGetDataResponse_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsGetDataResponse_Data(t interface {
	mock.TestingT
	Cleanup(func())
}) *isGetDataResponse_Data {
	mock := &isGetDataResponse_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
