// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "github.com/flyteorg/flyte/flyteidl/gen/pb-go/flyteidl/service"
	mock "github.com/stretchr/testify/mock"
)

// SyncAgentServiceServer is an autogenerated mock type for the SyncAgentServiceServer type
type SyncAgentServiceServer struct {
	mock.Mock
}

// ExecuteTaskSync provides a mock function with given fields: _a0
func (_m *SyncAgentServiceServer) ExecuteTaskSync(_a0 service.SyncAgentService_ExecuteTaskSyncServer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTaskSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(service.SyncAgentService_ExecuteTaskSyncServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSyncAgentServiceServer creates a new instance of SyncAgentServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncAgentServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncAgentServiceServer {
	mock := &SyncAgentServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
