// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSyncConnectorServiceServer is an autogenerated mock type for the UnsafeSyncConnectorServiceServer type
type UnsafeSyncConnectorServiceServer struct {
	mock.Mock
}

type UnsafeSyncConnectorServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeSyncConnectorServiceServer) EXPECT() *UnsafeSyncConnectorServiceServer_Expecter {
	return &UnsafeSyncConnectorServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSyncConnectorServiceServer provides a mock function with given fields:
func (_m *UnsafeSyncConnectorServiceServer) mustEmbedUnimplementedSyncConnectorServiceServer() {
	_m.Called()
}

// UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSyncConnectorServiceServer'
type UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSyncConnectorServiceServer is a helper method to define mock.On call
func (_e *UnsafeSyncConnectorServiceServer_Expecter) mustEmbedUnimplementedSyncConnectorServiceServer() *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call {
	return &UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSyncConnectorServiceServer")}
}

func (_c *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call) Run(run func()) *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call) Return() *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call) RunAndReturn(run func()) *UnsafeSyncConnectorServiceServer_mustEmbedUnimplementedSyncConnectorServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeSyncConnectorServiceServer creates a new instance of UnsafeSyncConnectorServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeSyncConnectorServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeSyncConnectorServiceServer {
	mock := &UnsafeSyncConnectorServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
