// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeIdentityServiceServer is an autogenerated mock type for the UnsafeIdentityServiceServer type
type UnsafeIdentityServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedIdentityServiceServer provides a mock function with given fields:
func (_m *UnsafeIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {
	_m.Called()
}
