// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	service "github.com/flyteorg/flyte/flyteidl/gen/pb-go/flyteidl/service"

	watch "github.com/flyteorg/flyte/flyteidl/gen/pb-go/flyteidl/watch"
)

// WatchServiceClient is an autogenerated mock type for the WatchServiceClient type
type WatchServiceClient struct {
	mock.Mock
}

type WatchServiceClient_WatchExecutionStatusUpdates struct {
	*mock.Call
}

func (_m WatchServiceClient_WatchExecutionStatusUpdates) Return(_a0 service.WatchService_WatchExecutionStatusUpdatesClient, _a1 error) *WatchServiceClient_WatchExecutionStatusUpdates {
	return &WatchServiceClient_WatchExecutionStatusUpdates{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *WatchServiceClient) OnWatchExecutionStatusUpdates(ctx context.Context, in *watch.WatchExecutionStatusUpdatesRequest, opts ...grpc.CallOption) *WatchServiceClient_WatchExecutionStatusUpdates {
	c_call := _m.On("WatchExecutionStatusUpdates", ctx, in, opts)
	return &WatchServiceClient_WatchExecutionStatusUpdates{Call: c_call}
}

func (_m *WatchServiceClient) OnWatchExecutionStatusUpdatesMatch(matchers ...interface{}) *WatchServiceClient_WatchExecutionStatusUpdates {
	c_call := _m.On("WatchExecutionStatusUpdates", matchers...)
	return &WatchServiceClient_WatchExecutionStatusUpdates{Call: c_call}
}

// WatchExecutionStatusUpdates provides a mock function with given fields: ctx, in, opts
func (_m *WatchServiceClient) WatchExecutionStatusUpdates(ctx context.Context, in *watch.WatchExecutionStatusUpdatesRequest, opts ...grpc.CallOption) (service.WatchService_WatchExecutionStatusUpdatesClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 service.WatchService_WatchExecutionStatusUpdatesClient
	if rf, ok := ret.Get(0).(func(context.Context, *watch.WatchExecutionStatusUpdatesRequest, ...grpc.CallOption) service.WatchService_WatchExecutionStatusUpdatesClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.WatchService_WatchExecutionStatusUpdatesClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *watch.WatchExecutionStatusUpdatesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
