# WARNING: THIS FILE IS MANAGED IN THE 'BOILERPLATE' REPO AND COPIED TO OTHER REPOSITORIES.
# ONLY EDIT THIS FILE FROM WITHIN THE 'FLYTEORG/BOILERPLATE' REPOSITORY:
# 
# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst

issues:
  exclude:
    - copylocks
  exclude-dirs:
    - pkg/client

linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
