# This rule is not used by the project executor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the flyte.org.flyte.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: executor
    app.kubernetes.io/managed-by: kustomize
  name: taskaction-editor-role
rules:
- apiGroups:
  - flyte.org.flyte.org
  resources:
  - taskactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flyte.org.flyte.org
  resources:
  - taskactions/status
  verbs:
  - get
