helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: flyte-sandbox
  releaseName: flyte-sandbox
  namespace: flyte
  valuesInline:
    flyte-binary:
      flyteconnector:
        enabled: True
namespace: flyte
resources:
- ../namespace.yaml

patchesStrategicMerge:
  - add-connector-secret-patch.yaml
