// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

type Publisher_Expecter struct {
	mock *mock.Mock
}

func (_m *Publisher) EXPECT() *Publisher_Expecter {
	return &Publisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, notificationType, msg
func (_m *Publisher) Publish(ctx context.Context, notificationType string, msg protoiface.MessageV1) error {
	ret := _m.Called(ctx, notificationType, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, protoiface.MessageV1) error); ok {
		r0 = rf(ctx, notificationType, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Publisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationType string
//   - msg protoiface.MessageV1
func (_e *Publisher_Expecter) Publish(ctx interface{}, notificationType interface{}, msg interface{}) *Publisher_Publish_Call {
	return &Publisher_Publish_Call{Call: _e.mock.On("Publish", ctx, notificationType, msg)}
}

func (_c *Publisher_Publish_Call) Run(run func(ctx context.Context, notificationType string, msg protoiface.MessageV1)) *Publisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(protoiface.MessageV1))
	})
	return _c
}

func (_c *Publisher_Publish_Call) Return(_a0 error) *Publisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_Publish_Call) RunAndReturn(run func(context.Context, string, protoiface.MessageV1) error) *Publisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
