{{- if and .Values.flytepropeller.enabled .Values.flytepropeller.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "flyte.namespace" . }}
  name: {{ template "flytepropeller.name" . }}
  labels: {{ include "flytepropeller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      protocol: TCP
      port: {{ index .Values.configmap.core.propeller "prof-port" }}
    {{- with .Values.flytepropeller.service.additionalPorts -}}
    {{ tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  selector: {{ include "flytepropeller.selectorLabels" . | nindent 4 }}
{{- end }}
