// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SecretManager is an autogenerated mock type for the SecretManager type
type SecretManager struct {
	mock.Mock
}

type SecretManager_Get struct {
	*mock.Call
}

func (_m SecretManager_Get) Return(_a0 string, _a1 error) *SecretManager_Get {
	return &SecretManager_Get{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *SecretManager) OnGet(ctx context.Context, key string) *SecretManager_Get {
	c_call := _m.On("Get", ctx, key)
	return &SecretManager_Get{Call: c_call}
}

func (_m *SecretManager) OnGetMatch(matchers ...interface{}) *SecretManager_Get {
	c_call := _m.On("Get", matchers...)
	return &SecretManager_Get{Call: c_call}
}

// Get provides a mock function with given fields: ctx, key
func (_m *SecretManager) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
