DEFAULT_UPLOAD_CHUNK_SIZE = 50 * 2**20  # 50MB
DEFAULT_CONCURRENT_UPLOAD = 4
SINGLE_OBJECT_UPLOAD_LIMIT = 5 * 2**30  # 5GB
DEFAULT_DOWNLOAD_CHUNK_SIZE = 50 * 2**20  # 50MB
DEFAULT_CONCURRENT_DOWNLOAD = 4
DEFAULT_DOWNLOAD_BODY_READ_SIZE = 2**16  # from s3fs
