run:
  skip-dirs:
    - pkg/client
linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - gci
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - protogetter
linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
  gosec:
    excludes:
      - G601 # disable the rule G601 since its not relevant in go 1.22+
  goconst:
    ignore-tests: true
issues:
  exclude:
    - copylocks

