{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-core.consoleName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flyte-core.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flyte-core.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: console
        {{- with .Values.commonLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.console.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- if or .Values.commonAnnotations .Values.console.podAnnotations }}
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.console.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.console.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: console
          image: {{ printf "%s:%s" .Values.console.image.repository .Values.console.image.tag | quote }}
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.console.containerPort }}
              protocol: TCP
          {{- with .Values.console.env }}
          env:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.console.basePath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.console.basePath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.console.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.console.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
