// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	store "github.com/eko/gocache/lib/v4/store"
	mock "github.com/stretchr/testify/mock"
)

// StringCache is an autogenerated mock type for the StringCache type
type StringCache[T any] struct {
	mock.Mock
}

type StringCache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *StringCache[T]) EXPECT() *StringCache_Expecter[T] {
	return &StringCache_Expecter[T]{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *StringCache[T]) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StringCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type StringCache_Clear_Call[T any] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StringCache_Expecter[T]) Clear(ctx interface{}) *StringCache_Clear_Call[T] {
	return &StringCache_Clear_Call[T]{Call: _e.mock.On("Clear", ctx)}
}

func (_c *StringCache_Clear_Call[T]) Run(run func(ctx context.Context)) *StringCache_Clear_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StringCache_Clear_Call[T]) Return(_a0 error) *StringCache_Clear_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringCache_Clear_Call[T]) RunAndReturn(run func(context.Context) error) *StringCache_Clear_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key
func (_m *StringCache[T]) Delete(ctx context.Context, key any) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StringCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StringCache_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key any
func (_e *StringCache_Expecter[T]) Delete(ctx interface{}, key interface{}) *StringCache_Delete_Call[T] {
	return &StringCache_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *StringCache_Delete_Call[T]) Run(run func(ctx context.Context, key any)) *StringCache_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(any))
	})
	return _c
}

func (_c *StringCache_Delete_Call[T]) Return(_a0 error) *StringCache_Delete_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringCache_Delete_Call[T]) RunAndReturn(run func(context.Context, any) error) *StringCache_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *StringCache[T]) Get(ctx context.Context, key any) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, any) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, any) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StringCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StringCache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key any
func (_e *StringCache_Expecter[T]) Get(ctx interface{}, key interface{}) *StringCache_Get_Call[T] {
	return &StringCache_Get_Call[T]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *StringCache_Get_Call[T]) Run(run func(ctx context.Context, key any)) *StringCache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(any))
	})
	return _c
}

func (_c *StringCache_Get_Call[T]) Return(_a0 string, _a1 error) *StringCache_Get_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StringCache_Get_Call[T]) RunAndReturn(run func(context.Context, any) (string, error)) *StringCache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with no fields
func (_m *StringCache[T]) GetType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StringCache_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type StringCache_GetType_Call[T any] struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *StringCache_Expecter[T]) GetType() *StringCache_GetType_Call[T] {
	return &StringCache_GetType_Call[T]{Call: _e.mock.On("GetType")}
}

func (_c *StringCache_GetType_Call[T]) Run(run func()) *StringCache_GetType_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StringCache_GetType_Call[T]) Return(_a0 string) *StringCache_GetType_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringCache_GetType_Call[T]) RunAndReturn(run func() string) *StringCache_GetType_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: ctx, options
func (_m *StringCache[T]) Invalidate(ctx context.Context, options ...store.InvalidateOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...store.InvalidateOption) error); ok {
		r0 = rf(ctx, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StringCache_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type StringCache_Invalidate_Call[T any] struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - options ...store.InvalidateOption
func (_e *StringCache_Expecter[T]) Invalidate(ctx interface{}, options ...interface{}) *StringCache_Invalidate_Call[T] {
	return &StringCache_Invalidate_Call[T]{Call: _e.mock.On("Invalidate",
		append([]interface{}{ctx}, options...)...)}
}

func (_c *StringCache_Invalidate_Call[T]) Run(run func(ctx context.Context, options ...store.InvalidateOption)) *StringCache_Invalidate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]store.InvalidateOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(store.InvalidateOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *StringCache_Invalidate_Call[T]) Return(_a0 error) *StringCache_Invalidate_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringCache_Invalidate_Call[T]) RunAndReturn(run func(context.Context, ...store.InvalidateOption) error) *StringCache_Invalidate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, object, options
func (_m *StringCache[T]) Set(ctx context.Context, key any, object string, options ...store.Option) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, object)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, any, string, ...store.Option) error); ok {
		r0 = rf(ctx, key, object, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StringCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type StringCache_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key any
//   - object string
//   - options ...store.Option
func (_e *StringCache_Expecter[T]) Set(ctx interface{}, key interface{}, object interface{}, options ...interface{}) *StringCache_Set_Call[T] {
	return &StringCache_Set_Call[T]{Call: _e.mock.On("Set",
		append([]interface{}{ctx, key, object}, options...)...)}
}

func (_c *StringCache_Set_Call[T]) Run(run func(ctx context.Context, key any, object string, options ...store.Option)) *StringCache_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]store.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(store.Option)
			}
		}
		run(args[0].(context.Context), args[1].(any), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *StringCache_Set_Call[T]) Return(_a0 error) *StringCache_Set_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringCache_Set_Call[T]) RunAndReturn(run func(context.Context, any, string, ...store.Option) error) *StringCache_Set_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewStringCache creates a new instance of StringCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStringCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *StringCache[T] {
	mock := &StringCache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
