// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	bitarray "github.com/flyteorg/flyte/v2/flytestdlib/bitarray"

	mock "github.com/stretchr/testify/mock"
)

// DownloadResponse is an autogenerated mock type for the DownloadResponse type
type DownloadResponse struct {
	mock.Mock
}

// GetCachedCount provides a mock function with no fields
func (_m *DownloadResponse) GetCachedCount() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachedCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetCachedResults provides a mock function with no fields
func (_m *DownloadResponse) GetCachedResults() *bitarray.BitSet {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachedResults")
	}

	var r0 *bitarray.BitSet
	if rf, ok := ret.Get(0).(func() *bitarray.BitSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitarray.BitSet)
		}
	}

	return r0
}

// GetResultsSize provides a mock function with no fields
func (_m *DownloadResponse) GetResultsSize() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResultsSize")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewDownloadResponse creates a new instance of DownloadResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDownloadResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *DownloadResponse {
	mock := &DownloadResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
