// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	catalog "github.com/flyteorg/flyte/v2/flyteplugins/go/tasks/pluginmachinery/catalog"
	mock "github.com/stretchr/testify/mock"
)

// Future is an autogenerated mock type for the Future type
type Future struct {
	mock.Mock
}

// GetResponseError provides a mock function with no fields
func (_m *Future) GetResponseError() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResponseError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetResponseStatus provides a mock function with no fields
func (_m *Future) GetResponseStatus() catalog.ResponseStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResponseStatus")
	}

	var r0 catalog.ResponseStatus
	if rf, ok := ret.Get(0).(func() catalog.ResponseStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(catalog.ResponseStatus)
	}

	return r0
}

// OnReady provides a mock function with given fields: handler
func (_m *Future) OnReady(handler catalog.ReadyHandler) {
	_m.Called(handler)
}

// NewFuture creates a new instance of Future. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *Future {
	mock := &Future{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
