# Queue Service Configuration

queue:
  server:
    host: "0.0.0.0"
    port: 8089
  kubernetes:
    namespace: "flyte"
    # Optional kubeconfig path. If not specified:
    #   1. Tries in-cluster config (when running in Kubernetes)
    #   2. Falls back to default kubeconfig (~/.kube/config)
    # kubeconfig: "/path/to/custom/kubeconfig"

logger:
  level: 4  # Info level
  show-source: true
