// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/lyft/flyteidl/gen/pb-go/flyteidl/core"
import mock "github.com/stretchr/testify/mock"

// InterfaceProvider is an autogenerated mock type for the InterfaceProvider type
type InterfaceProvider struct {
	mock.Mock
}

// GetExpectedInputs provides a mock function with given fields:
func (_m *InterfaceProvider) GetExpectedInputs() *core.ParameterMap {
	ret := _m.Called()

	var r0 *core.ParameterMap
	if rf, ok := ret.Get(0).(func() *core.ParameterMap); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ParameterMap)
		}
	}

	return r0
}

// GetExpectedOutputs provides a mock function with given fields:
func (_m *InterfaceProvider) GetExpectedOutputs() *core.VariableMap {
	ret := _m.Called()

	var r0 *core.VariableMap
	if rf, ok := ret.Get(0).(func() *core.VariableMap); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.VariableMap)
		}
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *InterfaceProvider) GetID() *core.Identifier {
	ret := _m.Called()

	var r0 *core.Identifier
	if rf, ok := ret.Get(0).(func() *core.Identifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Identifier)
		}
	}

	return r0
}
