run:
  skip-dirs:
    - pkg/client

linters:
  disable-all: true
  enable:
    - errcheck
    - gas
    - gci
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - protogetter
linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
  goconst:
    ignore-tests: true
