---
# Source: flyteagent/templates/agent/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flyteagent
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteagent
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteagent-v0.1.10
    app.kubernetes.io/managed-by: Helm
---
# Source: flyteagent/templates/agent/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flyteagent
  namespace: flyte
type: Opaque
data:
  username: User
---
# Source: flyteagent/templates/agent/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flyteagent
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteagent
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteagent-v0.1.10
    app.kubernetes.io/managed-by: Helm
  annotations: 
    projectcontour.io/upstream-protocol.h2c: grpc
spec:
  type: ClusterIP
  ports:
  - name: agent-grpc
    port: 8000
    protocol: TCP
    targetPort: agent-grpc
  selector: 
    app.kubernetes.io/name: flyteagent
    app.kubernetes.io/instance: flyte
---
# Source: flyteagent/templates/agent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyteagent
  namespace: flyte
  labels: 
    app.kubernetes.io/name: flyteagent
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyteagent-v0.1.10
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: flyteagent
      app.kubernetes.io/instance: flyte
  template:
    metadata:
      annotations:
      labels: 
        app.kubernetes.io/name: flyteagent
        app.kubernetes.io/instance: flyte
        helm.sh/chart: flyteagent-v0.1.10
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - command:
        - pyflyte
        - serve
        image: "ghcr.io/flyteorg/flyteagent:1.8.3"
        imagePullPolicy: "IfNotPresent"
        name: flyteagent
        volumeMounts:
        - mountPath: /etc/secrets
          name: flyteagent
        ports:
        - containerPort: 8000
          name: agent-grpc
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 200Mi
          requests:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 200Mi
      serviceAccountName: flyteagent
      volumes:
      - name: flyteagent
        secret:
          secretName: flyteagent
