package compile

//go:generate pflags Config --default-var DefaultCompileConfig --bind-default-var
var (
	DefaultCompileConfig = &Config{}
)

// Config stores the flags required by compile command
type Config struct {
	File string `json:"file" pflag:",Path to a flyte package file. Flyte packages are tgz files generated by pyflyte or jflyte."`
}
