{{- if .Values.sandbox.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flyte-console
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-devbox.labels" . | nindent 4 }}
spec:
  selector: {{- include "flyte-devbox.consoleSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
