// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	v1alpha1 "github.com/flyteorg/flyte/flytepropeller/pkg/apis/flyteworkflow/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// DAGStructureWithStartNode is an autogenerated mock type for the DAGStructureWithStartNode type
type DAGStructureWithStartNode struct {
	mock.Mock
}

type DAGStructureWithStartNode_Expecter struct {
	mock *mock.Mock
}

func (_m *DAGStructureWithStartNode) EXPECT() *DAGStructureWithStartNode_Expecter {
	return &DAGStructureWithStartNode_Expecter{mock: &_m.Mock}
}

// FromNode provides a mock function with given fields: id
func (_m *DAGStructureWithStartNode) FromNode(id string) ([]string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FromNode")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DAGStructureWithStartNode_FromNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromNode'
type DAGStructureWithStartNode_FromNode_Call struct {
	*mock.Call
}

// FromNode is a helper method to define mock.On call
//   - id string
func (_e *DAGStructureWithStartNode_Expecter) FromNode(id interface{}) *DAGStructureWithStartNode_FromNode_Call {
	return &DAGStructureWithStartNode_FromNode_Call{Call: _e.mock.On("FromNode", id)}
}

func (_c *DAGStructureWithStartNode_FromNode_Call) Run(run func(id string)) *DAGStructureWithStartNode_FromNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *DAGStructureWithStartNode_FromNode_Call) Return(_a0 []string, _a1 error) *DAGStructureWithStartNode_FromNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DAGStructureWithStartNode_FromNode_Call) RunAndReturn(run func(string) ([]string, error)) *DAGStructureWithStartNode_FromNode_Call {
	_c.Call.Return(run)
	return _c
}

// StartNode provides a mock function with no fields
func (_m *DAGStructureWithStartNode) StartNode() v1alpha1.ExecutableNode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartNode")
	}

	var r0 v1alpha1.ExecutableNode
	if rf, ok := ret.Get(0).(func() v1alpha1.ExecutableNode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ExecutableNode)
		}
	}

	return r0
}

// DAGStructureWithStartNode_StartNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNode'
type DAGStructureWithStartNode_StartNode_Call struct {
	*mock.Call
}

// StartNode is a helper method to define mock.On call
func (_e *DAGStructureWithStartNode_Expecter) StartNode() *DAGStructureWithStartNode_StartNode_Call {
	return &DAGStructureWithStartNode_StartNode_Call{Call: _e.mock.On("StartNode")}
}

func (_c *DAGStructureWithStartNode_StartNode_Call) Run(run func()) *DAGStructureWithStartNode_StartNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DAGStructureWithStartNode_StartNode_Call) Return(_a0 v1alpha1.ExecutableNode) *DAGStructureWithStartNode_StartNode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DAGStructureWithStartNode_StartNode_Call) RunAndReturn(run func() v1alpha1.ExecutableNode) *DAGStructureWithStartNode_StartNode_Call {
	_c.Call.Return(run)
	return _c
}

// ToNode provides a mock function with given fields: id
func (_m *DAGStructureWithStartNode) ToNode(id string) ([]string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ToNode")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DAGStructureWithStartNode_ToNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToNode'
type DAGStructureWithStartNode_ToNode_Call struct {
	*mock.Call
}

// ToNode is a helper method to define mock.On call
//   - id string
func (_e *DAGStructureWithStartNode_Expecter) ToNode(id interface{}) *DAGStructureWithStartNode_ToNode_Call {
	return &DAGStructureWithStartNode_ToNode_Call{Call: _e.mock.On("ToNode", id)}
}

func (_c *DAGStructureWithStartNode_ToNode_Call) Run(run func(id string)) *DAGStructureWithStartNode_ToNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *DAGStructureWithStartNode_ToNode_Call) Return(_a0 []string, _a1 error) *DAGStructureWithStartNode_ToNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DAGStructureWithStartNode_ToNode_Call) RunAndReturn(run func(string) ([]string, error)) *DAGStructureWithStartNode_ToNode_Call {
	_c.Call.Return(run)
	return _c
}

// NewDAGStructureWithStartNode creates a new instance of DAGStructureWithStartNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDAGStructureWithStartNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *DAGStructureWithStartNode {
	mock := &DAGStructureWithStartNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
