---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: minio-storage
          emptyDir: {}
      containers:
        - image: minio
          name: minio
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: miniostorage
            - name: MINIO_DEFAULT_BUCKETS
              value: my-s3-bucket
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-console
          volumeMounts:
            - name: minio-storage
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
spec:
  externalName: minio
  ports:
    - name: minio-api
      port: 9000
    - name: minio-console
      port: 9001
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: flyte
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /minio
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio
                port:
                  number: 9001
