---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-storage
          emptyDir: {}
      initContainers:
        - image: minio
          name: create-bucket
          command:
            - mkdir
            - /data/my-s3-bucket
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      containers:
        - image: minio
          name: minio
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: miniostorage
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              name: minio
          volumeMounts:
            - name: minio-storage
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
spec:
  externalName: minio
  ports:
    - port: 9000
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: flyte
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /minio
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio
                port:
                  number: 9000
