run:
  skip-files:
    # because we're skipping TLS verification - for now
    - cmd/entrypoints/serve.go
    - pkg/async/messages/sqs.go

linters:
  disable-all: true
  enable:
    - errcheck
    - gas
    - gci
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
  gosec:
    excludes:
      - G601 # disable the rule G601 since its not relevant in go 1.22+
issues:
  exclude:
    - copylocks
