run:
  skip-files:
    # because we're skipping TLS verification - for now
    - cmd/entrypoints/serve.go
    - pkg/async/messages/sqs.go

linters:
  disable-all: true
  enable:
    - errcheck
    - gas
    - gci
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - protogetter

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
  goconst:
    ignore-tests: true
issues:
  exclude-rules:
    - path: pkg/workflowengine/impl/prepare_execution.go
      text: "copies lock"
    - path: pkg/runtime/interfaces/application_configuration.go
      text: "G402: TLS InsecureSkipVerify may be true."
