name: Check Generated Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-generate-container:
    if: github.event.pull_request.head.repo.fork != true
    uses: ./.github/workflows/check-generate-container.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      base_ref: ${{ github.base_ref }}
  check-generate-local:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/check-generate-local.yml
  check-generate:
    needs: [check-generate-container, check-generate-local]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.check-generate-container.result }}" == "failure" ||
                "${{ needs.check-generate-local.result }}" == "failure" ]]; then
              exit 1
          fi
