name: Publish TypeScript Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gen/ts/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug Info
        run: |
          pwd
          ls -la
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
#      - name: Set up Node.js
#        uses: wyvox/action-setup-pnpm@v3
#        with:
#          node-version: 20
#          node-registry-url: 'https://registry.npmjs.org/'
#          node-version-file: './gen/ts/package.json'
      - name: Set version in npm package
        run: |
          # v1.2.3 get 1.2.3
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
          VERSION=$VERSION make update_npmversion
        shell: bash
      - run: |
          npm install
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          NPM_REGISTRY_URL="https://registry.npmjs.org/"
          npm publish --access=public --registry $NPM_REGISTRY_URL
