name: Publish TypeScript Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flyteorg/flyte/ci:v2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ./gen/ts/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          pwd
          ls -la

      - name: Set version in npm package
        run: |
          # v1.2.3 get 1.2.3
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
          VERSION=$VERSION make update_npmversion
        shell: bash

      - name: Install dependencies
        run: npm install
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          NPM_REGISTRY_URL="https://registry.npmjs.org/"
          npm publish --access=public --registry $NPM_REGISTRY_URL
