name: Update version in flyte.org
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  repository-dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Fetch version
        id: bump
        run: |
          # from refs/tags/v1.2.3 get 1.2.3
          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          echo "::set-output name=version::$VERSION"
      - name: Create an event for the release
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          repository: flyteorg/flyteorg.github.io
          event-type: release
          client-payload: '{"tag": "${{ steps.bump.outputs.version }}"}'
