name: Upstream Commit Explainer

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  pull-requests: write

jobs:
  check-upstream:
    name: Add explainer for upstremable commits
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '[x] To be upstreamed to OSS')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### :mega: Next step: upstream this commit

            @${{ github.event.pull_request.user.login }} run the following commands from a unionai/flyte repo and resolve any conflicts. Be sure to **update the commit message to be OSS friendly**.
            ```
            git fetch origin
            git remote get-url upstream &>/dev/null || git remote add upstream https://github.com/flyteorg/flyte.git
            git checkout -b union/upstream-${{ github.event.pull_request.merge_commit_sha }} usptream/master
            git cherry-pick -e ${{ github.event.pull_request.merge_commit_sha }}
            ```
            When done, `git push` and create a PR in flyteorg/flyte.

            Need help? Unsure if your change should be upstreamed? Ask in [#help-eng](https://unionai.slack.com/archives/C06RE4ZR5QQ)
